### ISSUE TITLE
WriteFileAtomic?

### ISSUE THREAD

**Issue by arnested** [ernoaapa/fetch-ssh-keys#4]
Two times I have been hit by the server running out of disk space (luckily just a test server).

The result was that when fetch-ssh-key tries to write an updated version of the ssh keys `WriteFile` only manages to truncate the authorized_keys file leaving it empty (and making key based ssh login impossible).

Maybe it would be an idea to use something like [WriteFileAtomic](https://github.com/youtube/vitess/blob/master/go/ioutil2/ioutil.go) in [master/output/file.go](https://github.com/ernoaapa/fetch-ssh-keys/blob/master/output/file.go) to make sure it is actually possible to write the files to disk?

**Comment by ernoaapa** [comment]
Thanks @arnested for reporting this! 
I'll try to look into this during the weekend. Or if you happen to have tested fix for this, please throw a PR.

**Comment by arnested** [comment]
I'll give it a try ... my first go pull request :smile:

**Comment by arnested** [comment]
Well, that seemed surprisingly simple. Please review and give feedback: #5.

**Comment by ernoaapa** [comment]
Thank you! 👏
